spring:
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#spring:
#  datasource:
#    url: jdbc:mariadb://localhost:3306/celiaquia
#    username: celiaquia
#    password: celiaquia123
#    driver-class-name: org.mariadb.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create-drop
